# Generated by Django 5.1.3 on 2024-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_caritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
